ConcealNetwork/conceal-website

defi/index.php
conceal-earn replacing blockchain "banking"
=> conceal-earn re-branding

index.php
some description corrections, conceal-earn rebranding, etc
=> index updates

about/index.php, index.php
=> index subtitle

clive/index.php, donate/index.php, in-the-media/index.php, index.php, lang/en.json, roadmap/index.php
rename "privacy-protected" to privacy-"preserving" across the website pages
=> privacy-preserving branding

index.php
update menu and title in the homepage
=> homepage retouch

index.php, landing/include/topjs.html
=> awesome font library

index.php
rebranding to match the official branding guide
=> apps renaming

community/index.php
=> update community page

index.php
=> main menu update

index.php, privacy/index.html, tc/index.html
fixing copyright and adding web wallet to ToS pages
=> adding web wallet to TOS pages

index.php
removing markets button in the top menu
=> removing button

index.php
removing support and donate buttons from the main menu
=> updating top menu

index.php
fixed support link and moved bridge to products section
=> updating menu

index.php
added developers section, made external  links opening in a new tab, renamed ccx-labs and main title
=> adding developers section

index.php
changelog:
- removed conceal-pay
- forced external urls to open in a new window
- added medium url to news
=> tidying up the menus

app/index.php, index.php
fixed homepage span and typo on app page
=> fix homepage span

index.php
reworked conceal.network banner over buttons
=> homepage centre rework

index.php
reordered top menu, updated download links and redone wallets section
=> menu reorder

index.php
renaming mobile and app titles on wallets section
=> uniformising titles in wallets section

index.php
=> removing conceal-id

about/index.php
shortened the intro to make it lighter and clearer for the reader
=> update about intro

index.php
match intro on 1st page with about section
=> update intro in index

index.php
changed subtitle and added a link to about page
=> about section update

index.php
=> adding contact link

index.php
including bridge in footer links
=> including bridge in footer links

index.php
=> top menu and url format

index.php
re-categorization of the top menu and reordering of the submenus
=> top menu 2024

about/index.php
=> updating about landing page
